import { Whimsy as WhimsyType } from "../types";

export const whimsies: Array<WhimsyType> = [
    {
        url: '',
        iconURL: '/mood-ring-icon.png',
        title: 'digital mood ring',
        description: 'a mood ring, coded entirely in css, that changes color based on the expression on your face',
        disabled: true,
    },

    {
        url: '',
        iconURL: '/race-icon.png',
        title: 'aeki pick race',
        description: 'compare various computer-generated pick paths at labyrinthine Norwegian furniture store AEKI',
        disabled: true,
    },

    {
        url: '',
        iconURL: '/r2d2-icon.png',
        title: "BIM's bakery",
        description: 'before there was ChatGPT, there was BIM. read some recipes generated by the transformer I fine-tuned on a corpus of 5,000 dessert recipes',
        disabled: true
    }
]