import { Whimsy as WhimsyType } from "../pages/whimsy/types";

export const whimsies: Array<WhimsyType> = [
    {
        url: '',
        title: 'digital mood ring',
        description: 'a mood ring, coded entirely in css, that changes color based on the expression on your face',
        disabled: true,
    },

    {
        url: '',
        title: 'aeki pick race',
        description: 'compare various computer-generated pick paths at labyrinthine Norwegian furniture store AEKI',
        disabled: true,
    },

    {
        url: '',
        title: "BIM's Bakery",
        description: 'before there was ChatGPT, there was BIM. read some recipes generated by the transformer I finetuned on a corpus of 5000 dessert recipes',
        disabled: true
    }
]